<ul class="menu">
	<!--<li <?php echo menu_active('users','profiles')?>><a href="users/admin/profiles">โพรไฟล์</a></li>-->
    <li <?php echo menu_active('users','administrators')?>><a href="users/admin/administrators">ผู้ดูแล</a></li>
	<li <?php echo menu_active('users','users')?>><a href="users/admin/users">สมาชิก</a></li>
    <li <?php echo menu_active('products','categories')?>><a href="products/admin/categories/index/">สินค้า</a></li>
	<li <?php echo menu_active('zicons','zicons')?>><a href="zicons/admin/zicons/index/">ไอค่อนสินค้า</a></li>
	<li <?php echo menu_active('znews','znews')?>><a href="znews/admin/znews/index/">ข่าวสารและโปรโมชั่น</a></li>
	<li <?php echo menu_active('resellers','categories')?>><a href="resellers/admin/categories/index/">ตัวแทนจำหน่าย</a></li>
    <li <?php echo menu_active('applicants','applicants')?>><a href="applicants/admin/applicants/index/">ใบสมัครตัวแทนจำหน่าย</a></li>
	<li <?php echo menu_active('contacts','contacts')?>><a href="contacts/admin/contacts/index/">ติดต่อเรา</a></li>
	<!--<li <?php echo menu_active('galleries','galleries')?>><a href="galleries/admin/galleries/index/">แกลลอรี่</a></li>-->
	<li <?php echo menu_active('abouts','abouts')?>><a href="abouts/admin/abouts/index/">เกี่ยวกับเรา</a></li>
	<li <?php echo menu_active('abouts','address')?>><a href="abouts/admin/address/index/">ที่อยู่บริษัท</a></li>
	<li <?php echo menu_active('partners','partners')?>><a href="partners/admin/partners/index/">พาร์ทเนอร์</a></li>
    <li <?php echo menu_active('brochures','brochures')?>><a href="brochures/admin/brochures/index/">โบรชัวร์</a></li>
	<li <?php echo menu_active('softwares','softwares')?>><a href="softwares/admin/softwares/index/">ซอฟแวร์</a></li>
    <li <?php echo menu_active('wallpapers','categories')?>><a href="wallpapers/admin/categories/index/">วอลเปเปอร์</a></li>
    <li <?php echo menu_active('manuals','manuals')?>><a href="manuals/admin/manuals/index/">คู่มือ</a></li>
	<!--<li <?php echo menu_active('intropages','intropages')?>><a href="intropages/admin/intropages/index/">จัดการหน้าแรก</a></li>-->
    <li <?php echo menu_active('registers','registers')?>><a href="registers/admin/registers/index/">จัดการหน้าสมัครสมาชิก</a></li>
	<li <?php echo menu_active('hilights','hilights')?>><a href="hilights/admin/hilights/index/">ไฮไลท์</a></li>
    <li <?php echo menu_active('hmenus','hmenus')?>><a href="hmenus/admin/hmenus/index">เฮดเดอร์เมนู</a></li>
	<li <?php echo menu_active('fmenus','fmenus')?>><a href="fmenus/admin/fmenus/index">ฟุตเตอร์เมนู</a></li>
    <li <?php echo menu_active('submenus','submenus')?>><a href="submenus/admin/submenus/index">ซับเมนู</a></li>
    <li <?php echo menu_active('socials','socials')?>><a href="socials/admin/socials/index">Social Icon</a></li>
    <li <?php echo menu_active('whats','categories')?>><a href="whats/admin/categories/index/">What Fit in My Car</a></li>
    <li <?php echo menu_active('tips','tips')?>><a href="tips/admin/tips/index/">Tip & Technic</a></li>
    <li <?php echo menu_active('introduces','introduces')?>><a href="introduces/admin/introduces/index/">Introduce Product</a></li>
    <li <?php echo menu_active('connects','connects')?>><a href="connects/admin/connects/index/">Connects White Up</a></li>
</ul>